version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver
    environment:
      SA_PASSWORD: YourPass1!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=MyDb;User Id=sa;Password=YourPass1!;TrustServerCertificate=True;
    ports:
      - "5134:8080"
    networks:
      - app-network

volumes:
  mssqldata:
    driver: local

networks:
  app-network:
